"""add_doctor_review_validation_fields

Revision ID: 1d8041274718
Revises: cbbde3025d54
Create Date: 2026-04-15 14:07:03.403689+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d8041274718'
down_revision: Union[str, Sequence[str], None] = 'cbbde3025d54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cases', 'case_number',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('case_number_seq')"),
               existing_comment='Sequential display number, shown as AI-{n} in the UI',
               existing_nullable=True)
    op.add_column('doctor_reviews', sa.Column('is_ai_correct', sa.Boolean(), nullable=True, comment="Doctor's verdict: True=AI was correct, False=AI was wrong"))
    op.add_column('doctor_reviews', sa.Column('selected_differentials', sa.Text(), nullable=True, comment='JSON array of diagnosis names the doctor marked as correct (checkboxes)'))
    op.add_column('doctor_reviews', sa.Column('confidence_level', sa.String(length=20), nullable=True, comment="Doctor's confidence in confirmed diagnosis: low | high"))
    op.add_column('doctor_reviews', sa.Column('qa_history', sa.Text(), nullable=True, comment='JSON array of {question, answer} pairs from doctor Q&A rounds'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor_reviews', 'qa_history')
    op.drop_column('doctor_reviews', 'confidence_level')
    op.drop_column('doctor_reviews', 'selected_differentials')
    op.drop_column('doctor_reviews', 'is_ai_correct')
    op.alter_column('cases', 'case_number',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('case_number_seq'::regclass)"),
               existing_comment='Sequential display number, shown as AI-{n} in the UI',
               existing_nullable=True)
    # ### end Alembic commands ###
