"""add_image_url_to_messages

Revision ID: b8b5ccfc0300
Revises: aa11bb22cc33
Create Date: 2026-04-22 11:05:58.077470+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8b5ccfc0300'
down_revision: Union[str, Sequence[str], None] = 'aa11bb22cc33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cases', 'case_number',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('case_number_seq')"),
               existing_comment='Sequential display number, shown as AI-{n} in the UI',
               existing_nullable=True)
    op.alter_column('cases', 'visual_findings',
               existing_type=sa.TEXT(),
               comment='JSON: {clinical:{...}, dermoscopy:{...}, pathology:{...}} — populated by generate_visual_findings_task after doctor uploads images',
               existing_comment='JSON: {clinical:{...}, dermoscopy:{...}, pathology:{...}} — populated by generate_visual_findings_task',
               existing_nullable=True)
    op.alter_column('doctor_reviews', 'confirmed_diagnosis',
               existing_type=sa.TEXT(),
               comment='JSON array of confirmed diagnosis names — mirrors selected_differentials',
               existing_comment="Doctor's confirmed final diagnosis (may differ from AI's)",
               existing_nullable=True)
    op.add_column('messages', sa.Column('image_url', sa.String(length=2000), nullable=True, comment='Signed GCS URL of an image the patient attached to this answer'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'image_url')
    op.alter_column('doctor_reviews', 'confirmed_diagnosis',
               existing_type=sa.TEXT(),
               comment="Doctor's confirmed final diagnosis (may differ from AI's)",
               existing_comment='JSON array of confirmed diagnosis names — mirrors selected_differentials',
               existing_nullable=True)
    op.alter_column('cases', 'visual_findings',
               existing_type=sa.TEXT(),
               comment='JSON: {clinical:{...}, dermoscopy:{...}, pathology:{...}} — populated by generate_visual_findings_task',
               existing_comment='JSON: {clinical:{...}, dermoscopy:{...}, pathology:{...}} — populated by generate_visual_findings_task after doctor uploads images',
               existing_nullable=True)
    op.alter_column('cases', 'case_number',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('case_number_seq'::regclass)"),
               existing_comment='Sequential display number, shown as AI-{n} in the UI',
               existing_nullable=True)
    # ### end Alembic commands ###
