"""add_clinical_indicators_to_doctor_review

Revision ID: ac43a2a21a19
Revises: 1d8041274718
Create Date: 2026-04-15 16:42:07.263319+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac43a2a21a19'
down_revision: Union[str, Sequence[str], None] = '1d8041274718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cases', 'case_number',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('case_number_seq')"),
               existing_comment='Sequential display number, shown as AI-{n} in the UI',
               existing_nullable=True)
    op.add_column('doctor_reviews', sa.Column('clinical_indicators', sa.Text(), nullable=True, comment='JSON array of clinical indicator strings confirmed by the doctor'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor_reviews', 'clinical_indicators')
    op.alter_column('cases', 'case_number',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('case_number_seq'::regclass)"),
               existing_comment='Sequential display number, shown as AI-{n} in the UI',
               existing_nullable=True)
    # ### end Alembic commands ###
