"""widen_avatar_url_to_2000

Revision ID: 6f7f5f8c1465
Revises: ac43a2a21a19
Create Date: 2026-04-15 16:59:07.273658+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f7f5f8c1465'
down_revision: Union[str, Sequence[str], None] = 'ac43a2a21a19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cases', 'case_number',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('case_number_seq')"),
               existing_comment='Sequential display number, shown as AI-{n} in the UI',
               existing_nullable=True)
    op.alter_column('doctor_profiles', 'avatar_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=2000),
               comment='GCS signed URL for profile photo',
               existing_comment='GCS path to profile photo',
               existing_nullable=True)
    op.alter_column('patient_profiles', 'avatar_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=2000),
               comment='GCS signed URL for profile photo',
               existing_comment='GCS path to profile photo',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patient_profiles', 'avatar_url',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=500),
               comment='GCS path to profile photo',
               existing_comment='GCS signed URL for profile photo',
               existing_nullable=True)
    op.alter_column('doctor_profiles', 'avatar_url',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=500),
               comment='GCS path to profile photo',
               existing_comment='GCS signed URL for profile photo',
               existing_nullable=True)
    op.alter_column('cases', 'case_number',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('case_number_seq'::regclass)"),
               existing_comment='Sequential display number, shown as AI-{n} in the UI',
               existing_nullable=True)
    # ### end Alembic commands ###
