"""initial_schema

Revision ID: 7d9c393d2876
Revises: 
Create Date: 2026-04-06 08:39:02.891236+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d9c393d2876'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snomed_mappings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('diagnosis_text', sa.String(length=500), nullable=False, comment='Exact AI-generated diagnosis string used as cache key'),
    sa.Column('snomed_code', sa.String(length=50), nullable=True, comment='SNOMED CT concept ID (e.g. 9014002 for Psoriasis)'),
    sa.Column('snomed_term', sa.String(length=500), nullable=True, comment='Official SNOMED CT preferred term'),
    sa.Column('cached_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When this mapping was first cached'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snomed_mappings_diagnosis_text'), 'snomed_mappings', ['diagnosis_text'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID v4 primary key'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Unique email address — used for login and notifications'),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment='Display name shown in the app'),
    sa.Column('role', sa.Enum('PATIENT', 'DOCTOR', 'ADMIN', name='user_role_enum'), nullable=False, comment='patient | doctor | admin'),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='bcrypt hash. NULL for Google OAuth users.'),
    sa.Column('google_id', sa.String(length=255), nullable=True, comment='Google subject ID for OAuth users'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='False = account suspended. Cannot log in.'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='True after email confirmation link is clicked'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False, comment='The registered user who started the consultation'),
    sa.Column('doctor_id', sa.String(length=36), nullable=True, comment='Assigned doctor. NULL until doctor scans the QR.'),
    sa.Column('consultation_type', sa.Enum('NEW_COMPLAINT', 'FOLLOW_UP', name='consultation_type_enum'), nullable=False, comment='new_complaint | follow_up — patient selects at start'),
    sa.Column('has_visible_lesion', sa.Boolean(), nullable=False, comment='Determines which AI path runs (image vs complaint-only)'),
    sa.Column('consent_given', sa.Boolean(), nullable=False, comment='Must be True before any image upload is accepted'),
    sa.Column('consent_given_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when patient confirmed consent'),
    sa.Column('is_for_self', sa.Boolean(), nullable=False, comment='False when patient consults on behalf of a family member'),
    sa.Column('dependent_name', sa.String(length=255), nullable=True, comment='Name of the family member (if is_for_self=False)'),
    sa.Column('dependent_relationship', sa.String(length=100), nullable=True, comment='e.g. Son, Mother, Spouse (if is_for_self=False)'),
    sa.Column('dependent_dob', sa.Date(), nullable=True, comment='Date of birth of the family member'),
    sa.Column('dependent_gender', sa.String(length=50), nullable=True, comment='Gender of the family member'),
    sa.Column('ai_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='ai_status_enum'), nullable=False, comment='Celery pipeline state. Set by workers only.'),
    sa.Column('clinical_status', sa.Enum('ACTIVE', 'FOLLOW_UP_AVAILABLE', 'MONITORING', 'RESOLVED', name='clinical_status_enum'), nullable=False, comment='Doctor-set status. Shown as badge in patient History screen.'),
    sa.Column('presenting_complaint', sa.Text(), nullable=True, comment="Patient's initial complaint in their own words"),
    sa.Column('case_summary', sa.Text(), nullable=True, comment='AI-generated case summary shown to patient before QR code'),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True, comment='Active Celery task chain ID for status polling'),
    sa.Column('question_round', sa.Integer(), nullable=False, comment='Current Q&A round number (increments after each question set)'),
    sa.Column('max_question_rounds', sa.Integer(), nullable=False, comment='Set by question_numbers() AI call based on diagnosis complexity'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_ai_status'), 'cases', ['ai_status'], unique=False)
    op.create_index(op.f('ix_cases_clinical_status'), 'cases', ['clinical_status'], unique=False)
    op.create_index(op.f('ix_cases_doctor_id'), 'cases', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_cases_patient_id'), 'cases', ['patient_id'], unique=False)
    op.create_table('doctor_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('specialization', sa.String(length=255), nullable=True, comment="e.g. 'Dermatology', 'Trichology'"),
    sa.Column('license_number', sa.String(length=100), nullable=True, comment='Medical license / registration number'),
    sa.Column('clinic_name', sa.String(length=255), nullable=True, comment='Clinic or hospital name shown in the doctor profile'),
    sa.Column('clinic_schedule', sa.Text(), nullable=True, comment='JSON blob for weekly schedule. Parsed and rendered by the Flutter app.'),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False, comment='Push notification preference from Doctor Profile screen'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='GCS path to profile photo'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_profiles_user_id'), 'doctor_profiles', ['user_id'], unique=True)
    op.create_table('patient_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('patient_code', sa.String(length=20), nullable=False, comment='Human-readable ID shown on patient profile (e.g. ABC-5482-S). Doctors use this for manual case lookup.'),
    sa.Column('date_of_birth', sa.Date(), nullable=True, comment='Used to compute age displayed in the app'),
    sa.Column('gender', sa.String(length=50), nullable=True, comment='Male | Female | Other | Prefer not to say'),
    sa.Column('phone', sa.String(length=30), nullable=True, comment='Contact phone number shown on profile'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='GCS path to profile photo'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_profiles_patient_code'), 'patient_profiles', ['patient_code'], unique=True)
    op.create_index(op.f('ix_patient_profiles_user_id'), 'patient_profiles', ['user_id'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='The user this token was issued to'),
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='SHA-256 hex digest of the raw refresh token. Never store the raw token.'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Token is invalid after this UTC datetime (default: now + 30 days)'),
    sa.Column('revoked', sa.Boolean(), nullable=False, comment='True after logout or token rotation. Reject immediately.'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='When the token was revoked (logout / rotation)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_revoked'), 'refresh_tokens', ['revoked'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('case_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('gcs_path', sa.String(length=1000), nullable=False, comment='Full GCS object path: cases/{case_id}/images/{image_id}.jpg'),
    sa.Column('image_type', sa.Enum('SKIN', 'PRESCRIPTION', 'DERMOSCOPY', name='image_type_enum'), nullable=False, comment='skin | prescription | dermoscopy'),
    sa.Column('original_filename', sa.String(length=500), nullable=True, comment="Original filename from the patient's device"),
    sa.Column('mime_type', sa.String(length=100), nullable=False, comment='e.g. image/jpeg, image/png'),
    sa.Column('size_bytes', sa.Integer(), nullable=False, comment='File size in bytes — used for storage quota checks'),
    sa.Column('upload_order', sa.Integer(), nullable=False, comment='Position in the image set (0-indexed). Preserves display order.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_images_case_id'), 'case_images', ['case_id'], unique=False)
    op.create_table('case_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('gcs_path', sa.String(length=1000), nullable=False, comment='GCS path: cases/{case_id}/reports/report_{type}.pdf'),
    sa.Column('report_type', sa.Enum('DOCTOR', 'PATIENT', name='report_type_enum'), nullable=False, comment='doctor | patient'),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False, comment='When the PDF was generated'),
    sa.Column('download_count', sa.Integer(), nullable=False, comment='Number of times this report has been downloaded'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_reports_case_id'), 'case_reports', ['case_id'], unique=True)
    op.create_table('differential_diagnoses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False, comment='0 = initial differential (image only). Increments after each Q&A round.'),
    sa.Column('is_final', sa.Boolean(), nullable=False, comment="True for the last round's diagnosis — what the doctor reviews."),
    sa.Column('diagnosis_json', sa.Text(), nullable=False, comment='Full JSON: most_probable_diagnosis + differential_diagnoses list'),
    sa.Column('most_probable_diagnosis', sa.String(length=500), nullable=True, comment='Extracted diagnosis name — used for search and list display'),
    sa.Column('confidence', sa.String(length=20), nullable=True, comment='high | medium | low — extracted from diagnosis_json'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_differential_diagnoses_case_id'), 'differential_diagnoses', ['case_id'], unique=False)
    op.create_index(op.f('ix_differential_diagnoses_is_final'), 'differential_diagnoses', ['is_final'], unique=False)
    op.create_index(op.f('ix_differential_diagnoses_most_probable_diagnosis'), 'differential_diagnoses', ['most_probable_diagnosis'], unique=False)
    op.create_table('doctor_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False, comment='The doctor who performed this review'),
    sa.Column('confirmed_diagnosis', sa.String(length=500), nullable=True, comment="Doctor's confirmed final diagnosis (may differ from AI's)"),
    sa.Column('review_notes', sa.Text(), nullable=True, comment="Doctor's free-text clinical notes"),
    sa.Column('treatment_plan_json', sa.Text(), nullable=True, comment='JSON: medications, lifestyle_modifications, dietary_recommendations, prescription[]'),
    sa.Column('review_status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='review_status_enum'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True, comment="Timestamp when review_status became 'completed'"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_reviews_case_id'), 'doctor_reviews', ['case_id'], unique=True)
    op.create_index(op.f('ix_doctor_reviews_doctor_id'), 'doctor_reviews', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_reviews_review_status'), 'doctor_reviews', ['review_status'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('AI', 'PATIENT', 'DOCTOR', name='message_role_enum'), nullable=False, comment='ai | patient | doctor'),
    sa.Column('content', sa.Text(), nullable=False, comment='The question text (AI) or selected/typed answer (patient/doctor)'),
    sa.Column('round_number', sa.Integer(), nullable=False, comment='Which Q&A round this message belongs to'),
    sa.Column('question_index', sa.Integer(), nullable=True, comment='Position within a round (0-indexed). NULL for free-text replies.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_case_id'), 'messages', ['case_id'], unique=False)
    op.create_table('qr_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False, comment='URL-safe random token embedded in the QR image. Generated with secrets.token_urlsafe(32).'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Token expires at this UTC datetime (default: now + 24h)'),
    sa.Column('used', sa.Boolean(), nullable=False, comment='True after the doctor has scanned this token (single-use)'),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the doctor scanned the QR'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qr_tokens_case_id'), 'qr_tokens', ['case_id'], unique=False)
    op.create_index(op.f('ix_qr_tokens_token'), 'qr_tokens', ['token'], unique=True)
    op.create_table('todos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False, comment='The doctor who created this todo'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='Short task description (shown as the list item)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional longer notes / clinical context'),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True, comment='Optional target date for the action'),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when is_completed was set to True'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todos_case_id'), 'todos', ['case_id'], unique=False)
    op.create_index(op.f('ix_todos_doctor_id'), 'todos', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_todos_is_completed'), 'todos', ['is_completed'], unique=False)
    op.create_table('visual_descriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False, comment='0 = initial (no conversation context). Increments after each Q&A round.'),
    sa.Column('description_json', sa.Text(), nullable=False, comment='Full JSON from LLM: type_of_lesion, site, count, border, etc.'),
    sa.Column('overall_description', sa.Text(), nullable=True, comment='Plain-text summary extracted from description_json.overall_description'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visual_descriptions_case_id'), 'visual_descriptions', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visual_descriptions_case_id'), table_name='visual_descriptions')
    op.drop_table('visual_descriptions')
    op.drop_index(op.f('ix_todos_is_completed'), table_name='todos')
    op.drop_index(op.f('ix_todos_doctor_id'), table_name='todos')
    op.drop_index(op.f('ix_todos_case_id'), table_name='todos')
    op.drop_table('todos')
    op.drop_index(op.f('ix_qr_tokens_token'), table_name='qr_tokens')
    op.drop_index(op.f('ix_qr_tokens_case_id'), table_name='qr_tokens')
    op.drop_table('qr_tokens')
    op.drop_index(op.f('ix_messages_case_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_doctor_reviews_review_status'), table_name='doctor_reviews')
    op.drop_index(op.f('ix_doctor_reviews_doctor_id'), table_name='doctor_reviews')
    op.drop_index(op.f('ix_doctor_reviews_case_id'), table_name='doctor_reviews')
    op.drop_table('doctor_reviews')
    op.drop_index(op.f('ix_differential_diagnoses_most_probable_diagnosis'), table_name='differential_diagnoses')
    op.drop_index(op.f('ix_differential_diagnoses_is_final'), table_name='differential_diagnoses')
    op.drop_index(op.f('ix_differential_diagnoses_case_id'), table_name='differential_diagnoses')
    op.drop_table('differential_diagnoses')
    op.drop_index(op.f('ix_case_reports_case_id'), table_name='case_reports')
    op.drop_table('case_reports')
    op.drop_index(op.f('ix_case_images_case_id'), table_name='case_images')
    op.drop_table('case_images')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_revoked'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_patient_profiles_user_id'), table_name='patient_profiles')
    op.drop_index(op.f('ix_patient_profiles_patient_code'), table_name='patient_profiles')
    op.drop_table('patient_profiles')
    op.drop_index(op.f('ix_doctor_profiles_user_id'), table_name='doctor_profiles')
    op.drop_table('doctor_profiles')
    op.drop_index(op.f('ix_cases_patient_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_doctor_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_clinical_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_ai_status'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_snomed_mappings_diagnosis_text'), table_name='snomed_mappings')
    op.drop_table('snomed_mappings')
    # ### end Alembic commands ###
