"""add_ai_chat_sessions_and_messages

Revision ID: cbbde3025d54
Revises: e5f6a7b8c9d0
Create Date: 2026-04-15 06:34:22.603211+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbbde3025d54'
down_revision: Union[str, Sequence[str], None] = 'e5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_chat_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_chat_sessions_case_id'), 'ai_chat_sessions', ['case_id'], unique=False)
    op.create_index(op.f('ix_ai_chat_sessions_user_id'), 'ai_chat_sessions', ['user_id'], unique=False)
    op.create_table('ai_chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='ai_chat_role_enum'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ai_chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_chat_messages_session_id'), 'ai_chat_messages', ['session_id'], unique=False)
    op.alter_column('cases', 'case_number',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('case_number_seq')"),
               existing_comment='Sequential display number, shown as AI-{n} in the UI',
               existing_nullable=True)
    op.alter_column('cases', 'original_case_id',
               existing_type=sa.VARCHAR(length=36),
               comment='For follow-up cases — references the original case being followed up',
               existing_comment='FK to the original case for follow-up consultations',
               existing_nullable=True)
    op.alter_column('cases', 'consent_ai_analysis',
               existing_type=sa.BOOLEAN(),
               comment='Required. Must be True before any image upload is accepted.',
               existing_comment='Must be True before any image upload is accepted',
               existing_nullable=False)
    op.alter_column('cases', 'consent_ai_analysis_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when patient confirmed AI analysis consent',
               existing_comment='Timestamp when patient confirmed consent',
               existing_nullable=True)
    op.alter_column('cases', 'consent_research',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='Optional. Patient allows anonymized data for academic research.',
               existing_nullable=False)
    op.alter_column('cases', 'case_title',
               existing_type=sa.VARCHAR(length=255),
               comment="Most probable diagnosis name — shown as card title in case list (e.g. 'Eczema on hands')",
               existing_comment='Most probable AI diagnosis — shown as card title in case list',
               existing_nullable=True)
    op.alter_column('cases', 'symptom_tags',
               existing_type=sa.TEXT(),
               comment="JSON array of short symptom keywords parsed from key_supporting_features (e.g. ['Redness','Itching','Dry skin'])",
               existing_comment='JSON array of short symptom keyword strings for card chips',
               existing_nullable=True)
    op.alter_column('cases', 'red_flag_status',
               existing_type=postgresql.ENUM('not_checked', 'checking', 'clear', 'flagged', name='red_flag_status_enum'),
               server_default=None,
               comment='Status of the systemic / red flag check (Figma Basic Patient Flow step 8)',
               existing_comment='Status of the systemic / red flag check',
               existing_nullable=False)
    op.alter_column('dependents', 'gender',
               existing_type=sa.VARCHAR(length=50),
               comment='Male | Female | Other | Prefer not to say',
               existing_nullable=True)
    op.alter_column('verification_tokens', 'used',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_verification_tokens_used'), 'verification_tokens', ['used'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_tokens_used'), table_name='verification_tokens')
    op.alter_column('verification_tokens', 'used',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('dependents', 'gender',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Male | Female | Other | Prefer not to say',
               existing_nullable=True)
    op.alter_column('cases', 'red_flag_status',
               existing_type=postgresql.ENUM('not_checked', 'checking', 'clear', 'flagged', name='red_flag_status_enum'),
               server_default=sa.text("'not_checked'::red_flag_status_enum"),
               comment='Status of the systemic / red flag check',
               existing_comment='Status of the systemic / red flag check (Figma Basic Patient Flow step 8)',
               existing_nullable=False)
    op.alter_column('cases', 'symptom_tags',
               existing_type=sa.TEXT(),
               comment='JSON array of short symptom keyword strings for card chips',
               existing_comment="JSON array of short symptom keywords parsed from key_supporting_features (e.g. ['Redness','Itching','Dry skin'])",
               existing_nullable=True)
    op.alter_column('cases', 'case_title',
               existing_type=sa.VARCHAR(length=255),
               comment='Most probable AI diagnosis — shown as card title in case list',
               existing_comment="Most probable diagnosis name — shown as card title in case list (e.g. 'Eczema on hands')",
               existing_nullable=True)
    op.alter_column('cases', 'consent_research',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_comment='Optional. Patient allows anonymized data for academic research.',
               existing_nullable=False)
    op.alter_column('cases', 'consent_ai_analysis_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when patient confirmed consent',
               existing_comment='Timestamp when patient confirmed AI analysis consent',
               existing_nullable=True)
    op.alter_column('cases', 'consent_ai_analysis',
               existing_type=sa.BOOLEAN(),
               comment='Must be True before any image upload is accepted',
               existing_comment='Required. Must be True before any image upload is accepted.',
               existing_nullable=False)
    op.alter_column('cases', 'original_case_id',
               existing_type=sa.VARCHAR(length=36),
               comment='FK to the original case for follow-up consultations',
               existing_comment='For follow-up cases — references the original case being followed up',
               existing_nullable=True)
    op.alter_column('cases', 'case_number',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('case_number_seq'::regclass)"),
               existing_comment='Sequential display number, shown as AI-{n} in the UI',
               existing_nullable=True)
    op.drop_index(op.f('ix_ai_chat_messages_session_id'), table_name='ai_chat_messages')
    op.drop_table('ai_chat_messages')
    op.drop_index(op.f('ix_ai_chat_sessions_user_id'), table_name='ai_chat_sessions')
    op.drop_index(op.f('ix_ai_chat_sessions_case_id'), table_name='ai_chat_sessions')
    op.drop_table('ai_chat_sessions')
    # ### end Alembic commands ###
