"""
models/differential_diagnosis.py — AI Differential Diagnosis
=============================================================

Stores one differential diagnosis JSON per analysis round.
Generated by the AI analysis chain and refined after each Q&A round.

ROUND SYSTEM
-------------
Round 0: generate_first_differential() — image only, no conversation
Round 1+: diagnosis_analysis_from_conversation() — updates after each Q&A

`is_final = True` marks the last round's diagnosis as the definitive
AI output that the doctor sees. Only one row per case should have
is_final=True.

STORAGE STRATEGY
-----------------
diagnosis_json         — full JSON from LLM (most_probable + list of differentials)
most_probable_diagnosis — extracted for quick display and search
confidence             — "high" | "medium" | "low" extracted from JSON

GUARD (ISS-001)
---------------
Only ONE differential is generated per round — not three in parallel.
The old code ran 3 concurrent analysis chains. This model enforces
the sequential pattern by having one row per (case_id, round_number).
"""

from sqlalchemy import Boolean, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.models.base import Base, TimestampMixin, new_uuid


class DifferentialDiagnosis(TimestampMixin, Base):
    """
    One AI-generated differential per case analysis round.
    """

    __tablename__ = "differential_diagnoses"

    # ------------------------------------------------------------------ #
    # Primary Key
    # ------------------------------------------------------------------ #
    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_uuid)

    # ------------------------------------------------------------------ #
    # Foreign Key
    # ------------------------------------------------------------------ #
    case_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("cases.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # ------------------------------------------------------------------ #
    # Round & Finality
    # ------------------------------------------------------------------ #
    round_number: Mapped[int] = mapped_column(
        Integer,
        default=0,
        nullable=False,
        comment="0 = initial differential (image only). "
                "Increments after each Q&A round.",
    )
    is_final: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        nullable=False,
        index=True,
        comment="True for the last round's diagnosis — what the doctor reviews.",
    )

    # ------------------------------------------------------------------ #
    # AI Output
    # ------------------------------------------------------------------ #
    diagnosis_json: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Full JSON: most_probable_diagnosis + differential_diagnoses list",
    )
    most_probable_diagnosis: Mapped[str | None] = mapped_column(
        String(500),
        nullable=True,
        index=True,
        comment="Extracted diagnosis name — used for search and list display",
    )
    confidence: Mapped[str | None] = mapped_column(
        String(20),
        nullable=True,
        comment="high | medium | low — extracted from diagnosis_json",
    )

    # ------------------------------------------------------------------ #
    # Relationship
    # ------------------------------------------------------------------ #
    case: Mapped["Case"] = relationship(  # noqa: F821
        "Case",
        back_populates="differential_diagnoses",
    )

    def __repr__(self) -> str:
        return (
            f"<DifferentialDiagnosis case={self.case_id!r} "
            f"round={self.round_number} "
            f"final={self.is_final} "
            f"diagnosis={self.most_probable_diagnosis!r}>"
        )
