"""
models/message.py — Conversation Message
=========================================

Stores the patient Q&A conversation history for a case.

One row = one message (question OR answer).

ROLES
------
- "ai"      : A question generated by the AI (shown to patient)
- "patient" : The patient's answer (selected from options or typed)
- "doctor"  : Used in doctor-side Q&A (doctor answers AI's clarifying questions)

ROUND AND INDEX
---------------
round_number:  which Q&A round this message belongs to (0, 1, 2...)
question_index: position within a round (0, 1, 2 for 3 questions per round)

This ordering is used to reconstruct the conversation history string
that gets passed back to the AI prompts in subsequent rounds.

WHY STORE AS TEXT AND NOT JSON?
--------------------------------
The patient selects from dropdown options, but we store the full
selected text (not an index). This makes the conversation readable
without looking up option lists — important for the AI prompt context
and for human review by the doctor.
"""

import enum

from sqlalchemy import Enum, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.models.base import Base, TimestampMixin, new_uuid


class MessageRole(str, enum.Enum):
    AI = "ai"
    PATIENT = "patient"
    DOCTOR = "doctor"


class Message(TimestampMixin, Base):
    """
    One message (question or answer) in a case's Q&A conversation.
    """

    __tablename__ = "messages"

    # ------------------------------------------------------------------ #
    # Primary Key
    # ------------------------------------------------------------------ #
    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=new_uuid)

    # ------------------------------------------------------------------ #
    # Foreign Key
    # ------------------------------------------------------------------ #
    case_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("cases.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # ------------------------------------------------------------------ #
    # Message Content
    # ------------------------------------------------------------------ #
    role: Mapped[MessageRole] = mapped_column(
        Enum(MessageRole, name="message_role_enum", create_type=True),
        nullable=False,
        comment="ai | patient | doctor",
    )
    content: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="The question text (AI) or selected/typed answer (patient/doctor)",
    )

    # ------------------------------------------------------------------ #
    # Ordering
    # ------------------------------------------------------------------ #
    round_number: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        comment="Which Q&A round this message belongs to",
    )
    question_index: Mapped[int | None] = mapped_column(
        Integer,
        nullable=True,
        comment="Position within a round (0-indexed). NULL for free-text replies.",
    )

    # ------------------------------------------------------------------ #
    # Relationship
    # ------------------------------------------------------------------ #
    case: Mapped["Case"] = relationship(  # noqa: F821
        "Case",
        back_populates="messages",
    )

    def __repr__(self) -> str:
        return (
            f"<Message id={self.id!r} "
            f"role={self.role} "
            f"round={self.round_number} "
            f"case={self.case_id!r}>"
        )
